import type { Metadata } from "next";
import { Londrina_Solid, Ubuntu_Mono } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu_Mono({ subsets: ["latin"], weight: ["400", "700"] });
const londrina = Londrina_Solid({
  subsets: ["latin"],
  weight: ["100", "300", "400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body className={londrina.className}>{children}</body>
    </html>
  );
}
