import type { Metadata } from "next";
import { Londrina_Solid, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import Background from "./_components/Background";
import { PresentationBlock } from "./_components/PresentationBlock";

const ubuntu = Ubuntu_Mono({ subsets: ["latin"], weight: ["400", "700"] });
const londrina = Londrina_Solid({
  subsets: ["latin"],
  weight: ["100", "300", "400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body className={`h-full ${londrina.className}`}>
        <main className="min-h-screen bg-hero-image bg-no-repeat bg-cover bg-fixed flex flex-col">
          <div className="">
            <Header></Header>
          </div>
          <div className="flex flex-col justify-between flex-grow">
            <div className="flex justify-center md:justify-end xl:justify-center mt-16 p-2 md:p-8">
              {children}
            </div>
            <PresentationBlock></PresentationBlock>
          </div>
        </main>
      </body>
    </html>
  );
}
